import { Pedido } from '@/types/pedido';

// Obtener fecha en formato YYYY-MM-DD
export function getTodayDateString(offsetDays = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
}

export const INITIAL_PEDIDOS: Pedido[] = [
  {
    id: 'PED-001',
    celular: '990983812',
    cliente: 'Camila Flores',
    producto: 'Ramo Rose',
    hecho: true,
    entregado: true,
    precio_producto: 30.0,
    costo_delivery: 0.0,
    pago_yape: 30.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '1:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Con todo mi amor para la persona más especial.',
    notas: 'Recoge en tienda a la 1pm puntual',
  },
  {
    id: 'PED-002',
    celular: '963238887',
    cliente: 'Dr. Víctor Quispe',
    producto: 'Ramo Dama de la Justicia',
    hecho: true,
    entregado: true,
    precio_producto: 50.0,
    costo_delivery: 8.0,
    pago_yape: 58.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '12:00 pm',
    tipo_entrega: 'Delivery',
    direccion: 'Jr. Lima 450, frente al Poder Judicial',
    dedicatoria: 'Muchas felicitaciones por tu logro profesional.',
    notas: 'Llamar al llegar',
  },
  {
    id: 'PED-003',
    celular: '921780243',
    cliente: 'Romina Condori',
    producto: 'Ramo Romina',
    hecho: true,
    entregado: true,
    precio_producto: 31.5,
    costo_delivery: 0.0,
    pago_yape: 31.5,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '1:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Feliz aniversario mi vida.',
  },
  {
    id: 'PED-004',
    celular: '902148756',
    cliente: 'Mary Torres',
    producto: 'Merienda Mery + Chocolate',
    hecho: true,
    entregado: false,
    precio_producto: 69.0,
    costo_delivery: 0.0,
    pago_yape: 69.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '1:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Que tengas un día maravilloso y dulce.',
    notas: 'Viene a recoger su hermana',
  },
  {
    id: 'PED-005',
    celular: '990600700',
    cliente: 'Luciana Ramos',
    producto: 'Ramo Linda',
    hecho: true,
    entregado: true,
    precio_producto: 40.0,
    costo_delivery: 9.0,
    pago_yape: 0.0,
    pago_efectivo: 49.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '9:00 am',
    tipo_entrega: 'Delivery',
    direccion: 'Av. El Sol 820, Puno',
    dedicatoria: 'Para la mujer más hermosa.',
  },
  {
    id: 'PED-006',
    celular: '974244331',
    cliente: 'Geraldine Mamani',
    producto: 'Ramo Geraldine + Chocolate',
    hecho: true,
    entregado: true,
    precio_producto: 58.0,
    costo_delivery: 0.0,
    pago_yape: 58.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(1),
    hora: '6:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Feliz cumpleaños amiga bella!',
  },
  {
    id: 'PED-007',
    celular: '931366524',
    cliente: 'Karen Zapana',
    producto: 'Collar + Pulsera Flor',
    hecho: true,
    entregado: true,
    precio_producto: 45.0,
    costo_delivery: 10.0,
    pago_yape: 45.0,
    pago_efectivo: 0.0,
    saldo: 10.0, // Saldo pendiente
    ciudad: 'Juliaca',
    fecha: getTodayDateString(1),
    hora: '11:00 am',
    tipo_entrega: 'Delivery',
    direccion: 'Jr. San Román 312, Juliaca',
    dedicatoria: 'Un detalle con mucho cariño para ti.',
    notas: 'Falta pagar el delivery S/ 10 al entregar',
  },
  {
    id: 'PED-008',
    celular: '978360356',
    cliente: 'Esteban Cárdenas',
    producto: 'Ramo Cumpleañero + Peluche',
    hecho: true,
    entregado: true,
    precio_producto: 70.0,
    costo_delivery: 5.0,
    pago_yape: 75.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(1),
    hora: '12:00 pm',
    tipo_entrega: 'Delivery',
    direccion: 'Jr. Los Incas 230, int 3',
    dedicatoria: '¡Feliz día! Que cumplas muchos años más.',
  },
  {
    id: 'PED-009',
    celular: '918389744',
    cliente: 'Diego Mendoza',
    producto: 'Ramo Amor (Rosas Rojas Premium)',
    hecho: true,
    entregado: false,
    precio_producto: 91.0,
    costo_delivery: 8.0,
    pago_yape: 99.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '6:00 pm',
    tipo_entrega: 'Delivery',
    direccion: 'Barrio Bellavista, calle Progreso 105',
    dedicatoria: 'Por muchos años más juntos, te amo.',
  },
  {
    id: 'PED-010',
    celular: '918822747',
    cliente: 'Sofía Apaza',
    producto: 'Peluche Lotso Cumpleaños',
    hecho: true,
    entregado: false,
    precio_producto: 18.0,
    costo_delivery: 0.0,
    pago_yape: 18.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '4:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Para mi sobrina favorita!',
  },
  {
    id: 'PED-011',
    celular: '980462113',
    cliente: 'Álvaro Huanca',
    producto: 'Ramo 4 Rosas Azules + Chocolates',
    hecho: false,
    entregado: false,
    precio_producto: 45.0,
    costo_delivery: 8.0,
    pago_yape: 30.0,
    pago_efectivo: 0.0,
    saldo: 23.0,
    ciudad: 'Puno',
    fecha: getTodayDateString(0),
    hora: '9:00 am',
    tipo_entrega: 'Delivery',
    direccion: 'Urb. Chanu Chanu, Jr. Arequipa 550',
    dedicatoria: 'Siempre estaré a tu lado. Te quiero.',
    notas: 'Ojo: rosas azules teñidas, falta saldo S/ 23',
  },
  {
    id: 'PED-012',
    celular: '951234567',
    cliente: 'Mariana Beltrán',
    producto: 'Ramo Mi Niña + Corona',
    hecho: false,
    entregado: false,
    precio_producto: 45.0,
    costo_delivery: 0.0,
    pago_yape: 45.0,
    pago_efectivo: 0.0,
    saldo: 0.0,
    ciudad: 'Juliaca',
    fecha: getTodayDateString(1),
    hora: '4:00 pm',
    tipo_entrega: 'Recojo',
    dedicatoria: 'Para la princesa de la casa.',
    notas: 'Empacar con moño rosado',
  }
];
